# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP-\u0430\u0434\u0440\u0435\u0441 \u043a\u043b\u0438\u0435\u043d\u0442\u0430')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0437\u0430\u043f\u0438\u0441\u0438')),
            ],
            options={
                'ordering': ['-time'],
                'verbose_name': '\u0422\u0440\u0435\u043a\u0435\u0440',
                'verbose_name_plural': '\u0422\u0440\u0435\u043a\u0435\u0440\u044b',
            },
        ),
    ]
