---
# a unix path-friendly name (IE, no spaces or special characters)
project_name: ip_tracker

# a system user for projects management
user: project_user

# the base path to install to. You should not need to change this.
install_root: /home/{{ user }}

# the correct wsgi_module value would be `base.wsgi`
wsgi_module: base.wsgi

# any directories that need to be added to the PYTHONPATH.
pythonpath: "{{ install_root }}/{{ project_name }}/src/applications"

# the git repository URL for the project
project_repo: git@github.com:solartune/ip_tracker.git

# a private key that has access to the repository URL
ssh_private_key: ~/.ssh/id_rsa

# The value of your django project's STATIC_ROOT settings.
# This will be the directory that django's `collectstatic` management command
# copies static files to, and it must be an absolute path. The default value
# here assumes that STATIC_ROOT is set in your settings.py like so:
# STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, 'static'))
static_root: "{{ install_root }}/{{ project_name }}/static_root"

media_root: "{{ install_root }}/{{ project_name }}/media_root"

# the dns name or names (space separated) for your server
server_name: ip-tracker.com www.ip-tracker.com

# database setup. Note that because this playbook doesn't touch the default
# postgres pg_hba.conf file, we use local password-based authentication for
# postgres and thus you need to provide a username and password, and your
# settings.py MUST set "localhost" or "127.0.0.1" as the HOST value. For
# example, the default settings here assume the following values in
# settings.py:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'HOST': 'localhost',
#         'NAME': 'hello',
#         'USER': 'hello',
#         'PASSWORD': 'changeme',
#     }
# }
db_name: ip_tracker
db_user: postgres
db_password: changeme

# apt packages, you should not need to change this unless you have packages
# listed in your requirements.txt that depend on system packages.
system_packages:
  - git
  - nginx
  - postgresql
  - postgresql-server-dev-all
  - python-pip
  - python-dev
  - python-psycopg2

# uwsgi vassals directory
vassals_dir: /etc/uwsgi/vassals/

# supervisor conf directory
supervisor_conf_dir: /etc/supervisor/
